using Godot;
using System;

/// <Summary>
/// Upgrade increases the amount of stardust generated per second.
/// </Summary>
public partial class CC02StardustBoost : Upgrade
{
	private int maxLevel = 5;
	
	public CC02StardustBoost() : base(Game.Instance.Data.CCUpgrades.U02StardustBoostLevel, "Stardust Generator Efficiency", 1){
		CalculateCost();
		
	}
	
	/// Returns an String with the description of the upgrade.
	public override String GetDescription(){
		return "Increases the amount of Stardust generated by the Universe Core. \n" +
		"Effect: +1 stardust / sec \n" +
		"Cost: " + cost + " Consciousness Core";
	}
	
	/// Calculates the cost for the current upgrade.
	public override void CalculateCost(){
		cost = baseCost;
	}
	
	/// Returns bool if upgrade can be bought.
	public override bool CanAfford(){
		if(Game.Instance.Data.ConsciousnessCore >= cost && level < maxLevel) return true;
		return false;
	}
	
	/// Consumes stardust to level up.
	public override void LevelUp(){
		if(level >= maxLevel) return;
		bool success = HandlerConsciousnessCore.Instance.ConsumeConsciousneddCores(cost);
		if(!success) return;
		level ++;
		Game.Instance.Data.CCUpgrades.U02StardustBoostLevel = level;
		
		HandlerCCUpgrades.Instance.OnCCUpgradeLevelUp(this);
	}
}
